---
- name: Install dependencies on web servers  # ✅ Added play name
  hosts: all
  become: true
  tasks:
    - name: Install system dependencies
      ansible.builtin.yum:
        name:
          - python3
          - python3-pip
        state: present

    - name: Install Flask using pip
      ansible.builtin.pip:
        name: flask
        executable: pip3
