- hosts: all
  become: true
  tasks:
    - name: Install system dependencies
      yum:
        name:
          - python3
          - python3-pip
          - nginx
        state: present
    - name: Install Flask
      pip:
        name: flask
